import { config } from './config'

const node_env = ['development', 'test', 'production'].includes(process.env.NODE_ENV ?? '')
  ? process.env.NODE_ENV as 'development' | 'test' | 'production'
  : 'development'

// 兼容层：结构化配置（config.ts）以历史扁平形状暴露，调用点逐步迁移到 config 后
// 本文件即可删除。新增配置请直接加到 config/default.yaml 和 config.ts 的 schema。
export const env = {
  NODE_ENV: node_env,
  DB_HOST: config.db.host,
  DB_PORT: config.db.port,
  DB_USER: config.db.user,
  DB_PASSWORD: config.db.password,
  DB_NAME: config.db.name,
  JWT_SECRET: config.app.auth.jwt.secret,
  JWT_EXPIRES_IN_DAYS: config.app.auth.jwt.expiresInDays,
  JWT_RENEW_BEFORE_DAYS: config.app.auth.jwt.renewBeforeDays,
  BCRYPT_ROUNDS: config.app.auth.bcryptRounds,
  ALIYUN_ACCESS_KEY_ID: config.aliyun.accessKeyId,
  ALIYUN_ACCESS_KEY_SECRET: config.aliyun.accessKeySecret,
  ALIYUN_DYPNSAPI_ENDPOINT: config.aliyun.dypns.endpoint,
  ALIYUN_DYPNSAPI_REGION_ID: config.aliyun.dypns.regionId,
  IDENTITY_COOKIE_NAME: config.app.identity.cookieName,
  IDENTITY_COOKIE_MAX_AGE_DAYS: config.app.identity.cookieMaxAgeDays,
  OTP_EXPIRES_MINUTES: config.app.otp.expiresMinutes,
  OTP_TIER1_DAILY_LIMIT: config.app.otp.tier1.dailyLimit,
  OTP_TIER1_COOLDOWN_MS: config.app.otp.tier1.cooldownMs,
  OTP_TIER2_DAILY_LIMIT: config.app.otp.tier2.dailyLimit,
  OTP_TIER2_COOLDOWN_MS: config.app.otp.tier2.cooldownMs,
  OTP_SMS_SIGN_NAME: config.aliyun.sms.signName,
  OTP_SMS_TEMPLATE_CODE: config.aliyun.sms.templateCode,
  OTP_SMS_SCHEME_NAME: config.aliyun.sms.schemeName,
  OTP_DEBUG: config.app.otp.debug,
  CAPTCHA_APP_ID: config.aliyun.captcha.appId,
  CAPTCHA_APP_KEY: config.aliyun.captcha.appKey,
  API_BASE: config.app.api.base,
  COOKIE_MAX_AGE_DAYS: config.app.auth.cookie.maxAgeDays,
  SESSION_MAX_AGE_DAYS: config.app.auth.session.maxAgeDays,
  SESSION_MAX_TOKEN_GENERATIONS: config.app.auth.session.maxTokenGenerations,
  COLOR_MODE_FALLBACK: config.app.colorMode.fallback,
  COLOR_MODE_COOKIE_NAME: config.app.colorMode.cookieName,
  TIMEZONE_COOKIE_NAME: config.app.timezone.cookieName,
  AUTH_TOKEN_COOKIE_NAME: config.app.auth.cookie.tokenName,
  AUTH_USER_COOKIE_NAME: config.app.auth.cookie.userName,
  SYNC_BROADCAST_CHANNEL_NAME: config.app.sync.broadcastChannelName,
  SYNC_CLIENT_ID_STORAGE_KEY: config.app.sync.clientIdStorageKey,
  MAX_AVATAR_SIZE_MB: config.app.avatar.maxSizeMb,
  MAX_CONTENT_ENCRYPT_SIZE_MB: config.app.content.encrypt.maxSizeMb,
  CONTENT_REDACT_MAX_DIMENSION: config.app.content.redact.maxDimension,
  CONTENT_STORY_TITLE_MAX_LENGTH: config.app.content.story.titleMaxLength,
  CONTENT_LINK_FILE_NAME_MAX_BYTES: config.app.content.link.fileNameMaxBytes,
  CONTENT_STORY_LABEL_MAX_BYTES: config.app.content.story.labelMaxBytes,
  CONTENT_STORY_DESC_MAX_BYTES: config.app.content.story.descMaxBytes,
  CONTENT_STORY_COVER_MAX_BYTES: config.app.content.story.coverMaxBytes,
  CONTENT_STORY_MARKDOWN_MAX_BYTES: config.app.content.story.markdownMaxBytes,
  CONTENT_DRAFT_SCHEMA_VERSION: config.app.content.draft.schemaVersion,
  CONTENT_DRAFT_STORAGE_PREFIX: config.app.content.draft.storagePrefix,
  CONTENT_DRAFT_AUTOSAVE_DELAY_MS: config.app.content.draft.autosaveDelayMs,
  CONTENT_UPLOAD_HANDLE_STORAGE_NAME: config.app.content.upload.handleStorageName,
  CONTENT_OPERATION_LOCK_TTL_SECONDS: config.app.content.operationLock.ttlSeconds,
  OSS_ENDPOINT: config.oss.endpoint,
  OSS_REGION: config.oss.region,
  OSS_BUCKET: config.oss.bucket,
  OSS_ACCESS_KEY_ID: config.oss.accessKeyId,
  OSS_ACCESS_KEY_SECRET: config.oss.accessKeySecret,
  OSS_FORCE_PATH_STYLE: config.oss.forcePathStyle,
  STATIC_BASE_URL: config.site.staticBaseUrl,
  SITE_URL: config.site.url,
  SITE_INDEXABLE: config.site.indexable,
  ONLINE_TIMEOUT_SECONDS: config.app.online.timeoutSeconds,
  PING_IDLE_INTERVAL_SECONDS: config.app.online.pingIdleIntervalSeconds,
  POLL_INTERVAL_SECONDS: config.app.online.pollIntervalSeconds,
  BILIBILI_FETCH_TIMEOUT_MS: config.app.content.bilibili.fetchTimeoutMs,
  BILIBILI_CACHE_TTL_MS: config.app.content.bilibili.cacheTtlMs,
  BILIBILI_NEGATIVE_CACHE_TTL_MS: config.app.content.bilibili.negativeCacheTtlMs,
  BILIBILI_FETCH_FAILURE_COOLDOWN_MS: config.app.content.bilibili.fetchFailureCooldownMs,
  REDIS_HOST: config.redis.host,
  REDIS_PORT: config.redis.port,
  REDIS_PASSWORD: config.redis.password,
  MQTT_HOST: config.mqtt.host,
  MQTT_PORT: config.mqtt.port,
  MQTT_WS_HOST: config.mqtt.web.wsHost,
  MQTT_WS_PORT: config.mqtt.web.wsPort,
  MQTT_WSS_PORT: config.mqtt.web.wssPort,
  MQTT_USERNAME: config.mqtt.username,
  MQTT_PASSWORD: config.mqtt.password,
  MQTT_QOS: config.mqtt.qos,
  MQTT_TOPIC_PREFIX: config.mqtt.topicPrefix,
  MQTT_CLIENT_ID_PREFIX_SERVER: config.mqtt.clientIdPrefixServer,
  MQTT_CLIENT_ID_PREFIX_WEB: config.mqtt.web.clientIdPrefix,
  MQTT_PUBLISH_QUEUE_SIZE: config.mqtt.publishQueueSize,
}
